//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minuteman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minuteman.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left key is required..
        /// </summary>
        internal static string CompositeUserActivityReport_Constructor_LeftKey_Required {
            get {
                return ResourceManager.GetString("CompositeUserActivityReport_Constructor_LeftKey_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is required..
        /// </summary>
        internal static string CompositeUserActivityReport_Constructor_Operation_Required {
            get {
                return ResourceManager.GetString("CompositeUserActivityReport_Constructor_Operation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right key is required..
        /// </summary>
        internal static string CompositeUserActivityReport_Constructor_RightKey_Required {
            get {
                return ResourceManager.GetString("CompositeUserActivityReport_Constructor_RightKey_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string CompositeUserActivityReport_PerformBitOperation_Unsupported {
            get {
                return ResourceManager.GetString("CompositeUserActivityReport_PerformBitOperation_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is required..
        /// </summary>
        internal static string UserActivityReport_Constructor_Required {
            get {
                return ResourceManager.GetString("UserActivityReport_Constructor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db cannot be negative..
        /// </summary>
        internal static string Validation_ValidateDb_Negative {
            get {
                return ResourceManager.GetString("Validation_ValidateDb_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required..
        /// </summary>
        internal static string Validation_ValidateEventName_Required {
            get {
                return ResourceManager.GetString("Validation_ValidateEventName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more users is negative number..
        /// </summary>
        internal static string Validation_ValidateUsers_Negative {
            get {
                return ResourceManager.GetString("Validation_ValidateUsers_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more users is required..
        /// </summary>
        internal static string Validation_ValidateUsers_Required {
            get {
                return ResourceManager.GetString("Validation_ValidateUsers_Required", resourceCulture);
            }
        }
    }
}
